USE [master]
GO

/****** Object:  Database [Pukimoni]    Script Date: 8/30/2023 7:46:27 PM ******/
CREATE DATABASE [Pukimoni]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Pukimoni', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Pukimoni.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Pukimoni_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Pukimoni_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Pukimoni].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Pukimoni] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Pukimoni] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Pukimoni] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Pukimoni] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Pukimoni] SET ARITHABORT OFF 
GO

ALTER DATABASE [Pukimoni] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Pukimoni] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Pukimoni] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Pukimoni] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Pukimoni] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Pukimoni] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Pukimoni] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Pukimoni] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Pukimoni] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Pukimoni] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Pukimoni] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Pukimoni] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Pukimoni] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Pukimoni] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Pukimoni] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Pukimoni] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Pukimoni] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Pukimoni] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Pukimoni] SET  MULTI_USER 
GO

ALTER DATABASE [Pukimoni] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Pukimoni] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Pukimoni] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Pukimoni] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Pukimoni] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Pukimoni] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Pukimoni] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Pukimoni] SET  READ_WRITE 
GO

